# Generated by Django 5.2.1 on 2025-05-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='accountNumber',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='bankCode',
            new_name='bank_code',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='identificationNumber',
            new_name='identification_number',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='taxNumber',
            new_name='tax_number',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
